# Generated by Django 4.2.3 on 2023-10-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_rename_old_differentiae_database"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="differentia",
            options={"verbose_name_plural": "differentiae"},
        ),
    ]
